wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: Triplet Network
dataset:
  desc: null
  value: Wikiart 1000
preprocessing:
  desc: null
  value: ResNet34
num_examples:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710344540.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
